import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";
import { copyFileSync, mkdirSync } from "node:fs";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const mode = process.argv[2];
const prod = mode === "production";
const watch = mode !== "production" && mode !== "development";

const BUILD_DIR = "dist";

function copyPluginAssets() {
	mkdirSync(BUILD_DIR, { recursive: true });
	copyFileSync("manifest.json", `${BUILD_DIR}/manifest.json`);
	copyFileSync("styles.css", `${BUILD_DIR}/styles.css`);
	copyFileSync(".gitignore-release", `${BUILD_DIR}/.gitignore`);
}

const copyAssetsPlugin = {
	name: "copy-plugin-assets",
	setup(build) {
		build.onEnd((result) => {
			if (result.errors.length > 0) {
				return;
			}
			copyPluginAssets();
		});
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules,
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: `${BUILD_DIR}/main.js`,
	minify: prod,
	plugins: [copyAssetsPlugin],
});

if (watch) {
	await context.watch();
} else {
	await context.rebuild();
	await context.dispose();
	process.exit(0);
}
